// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF_LAB4_31A3_OBIS_FRANCINE.Data;

#nullable disable

namespace PF_LAB4_31A3_OBIS_FRANCINE.Migrations
{
    [DbContext(typeof(RecipeDBContext))]
    [Migration("20250920065042_recipe")]
    partial class recipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PF_LAB4_31A3_OBIS_FRANCINE.Data.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ingredients = "",
                            Name = "Binangkal"
                        },
                        new
                        {
                            Id = 2,
                            Ingredients = "",
                            Name = "Adobo"
                        },
                        new
                        {
                            Id = 3,
                            Ingredients = "",
                            Name = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
